name: post_list_pagination_search
description: "A simple project for demonstrating search and pagination functionality using JsonPlaceholder for Post data."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.2
  theme_tailor: ^3.0.1
  get_it: ^8.0.3
  http: ^1.2.2
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  theme_tailor_annotation: ^3.0.1
  build_runner: ^2.4.14

flutter:

  uses-material-design: true